services:
  mongodb:
    image: mongo:latest
    environment:
      - 'MONGO_INITDB_DATABASE=moderator'
      - 'MONGO_INITDB_ROOT_PASSWORD=admin'
      - 'MONGO_INITDB_ROOT_USERNAME=admin'
    ports:
      - 27017:27017

  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      - 'ME_CONFIG_MONGODB_ADMINUSERNAME=admin'
      - 'ME_CONFIG_MONGODB_ADMINPASSWORD=admin'
      - 'ME_CONFIG_MONGODB_SERVER=mongodb'